In [19]:

from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
import pandas as pd
import numpy as np
import pickle
import os

INPUT_DIVIDER = 0.1
START_AMOUNT = 100

fileName = 'datasets/ETH_1H.csv'
delimeter = ','
df = pd.read_csv(fileName, delimiter=delimeter, index_col='Date')
df = df.dropna()
df.sort_index()

,Unix Timestamp,Symbol,Open,High,Low,Close,Volume
Date,,,,,,,
2016-05-09 13:00:00,1462798800,ETHUSD,0.00,12.00,0.00,9.55,432.562115
2016-05-09 14:00:00,1462802400,ETHUSD,9.55,10.00,9.55,10.00,235.774075
2016-05-09 15:00:00,1462806000,ETHUSD,10.00,10.00,9.99,9.99,10.973567
2016-05-09 16:00:00,1462809600,ETHUSD,9.99,9.99,9.79,9.83,62.379450
2016-05-09 17:00:00,1462813200,ETHUSD,9.83,9.83,9.48,9.49,329.553213
...,...,...,...,...,...,...,...
2020-04-15 20:00:00,1586980800000,ETHUSD,157.10,158.10,156.87,158.04,144.262622
2020-04-15 21:00:00,1586984400000,ETHUSD,158.04,158.31,157.16,157.18,55.244131
2020-04-15 22:00:00,1586988000000,ETHUSD,157.18,157.30,155.32,155.81,106.337279
2020-04-15 23:00:00,1586991600000,ETHUSD,155.81,155.81,151.39,152.94,4277.567299
2020-04-16 00:00:00,1586995200000,ETHUSD,152.94,152.94,150.39,150.39,650.188125

In [20]:

df.describe()

,Unix Timestamp,Open,High,Low,Close,Volume
count,3.449700e+04,34497.000000,34497.000000,34497.000000,34497.000000,34497.000000
mean,7.147761e+11,239.172160,240.988877,237.142926,239.176415,1563.625471
std,7.758756e+11,237.205512,239.468230,234.532649,237.202348,7003.461234
min,1.462799e+09,0.000000,6.150000,0.000000,6.100000,0.000000
25%,1.493845e+09,81.020000,82.120000,79.980000,81.020000,101.092334
50%,1.524892e+09,181.870000,182.770000,180.820000,181.870000,444.684817
75%,1.555938e+12,298.070000,299.920000,296.380000,298.070000,1508.711881
max,1.586995e+12,1417.540000,1420.010000,1388.990000,1417.540000,903102.685700

In [21]:

df['normal-high'] = (df['High'] -  df['High'].min()) / (df['High'].max()  - df['High'].min())
df['normal-low'] = (df['Low'] -  df['Low'].min()) / (df['Low'].max()  - df['Low'].min())
df['normal-open'] = (df['Open'] -  df['Open'].min()) / (df['Open'].max()  - df['Open'].min())
df['normal-close'] = (df['Close'] -  df['Close'].min()) / (df['Close'].max()  - df['Close'].min())

df['open-close']  = df['normal-open'] - df['normal-close']
df['low-high']  = df['normal-low'] - df['normal-high']

df['target'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0) 

featureColumns = ['open-close', 'low-high']

features = df[featureColumns]
target = df['target']

df.head(2)

,Unix Timestamp,Symbol,Open,High,Low,Close,Volume,normal-high,normal-low,normal-open,normal-close,open-close,low-high,target
Date,,,,,,,,,,,,,,
2020-04-16 00:00:00,1586995200000,ETHUSD,152.94,152.94,150.39,150.39,650.188125,0.103822,0.108273,0.107891,0.102229,0.005662,0.004451,1
2020-04-15 23:00:00,1586991600000,ETHUSD,155.81,155.81,151.39,152.94,4277.567299,0.105852,0.108993,0.109916,0.104036,0.005880,0.003141,1

In [22]:


X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=34)

model = XGBClassifier(n_estimators=6, learning_rate=0.1, max_depth=3000, random_state=5)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy xboost: {accuracy:.4f}")

Accuracy xboost: 0.9346

In [23]:
# after_2018 = y_pred["Year"] > 2018
# movies[after_2018]
predictedDf = pd.DataFrame(y_pred)
predictedDf

ones = predictedDf[0] > 0

zeroes = predictedDf[0] == 0
predictedDf[zeroes]

       0
0      0
1      0
5      0
6      0
7      0
...   ..
10344  0
10346  0
10347  0
10348  0
10349  0

[6111 rows x 1 columns]

In [24]:
predictedDf[ones]

       0
2      1
3      1
4      1
9      1
10     1
...   ..
10333  1
10335  1
10341  1
10342  1
10345  1

[4239 rows x 1 columns]

In [25]:

# os.path.dirname(__file__) #<-- absolute dir the script is in
script_dir = os.path.join(os.path.dirname('__file__')) 


rel_path = 'models/boost_classifier-' + fileName + '.pkl'
filename = os.path.join(script_dir, rel_path)

with open(filename, 'wb') as file:
    pickle.dump(model, file)

# Load the model
with open(filename, 'rb') as file:
    model = pickle.load(file)

In [ ]:
def calculateDollars(dollarsInput, inputPart):
      dlrsAmount = dollarsInput
      cryptoAmount = 0
      investAmount = inputPart * dlrsAmount

      for index, row in df[:].iterrows():
            predicted = model.predict([row[featureColumns]])[:][0]
            closePrice = row['Close']
            if predicted == 1 and dlrsAmount > investAmount and cryptoAmount == 0:
                  cryptoAmount = investAmount / closePrice
                  dlrsAmount = dlrsAmount - investAmount
            if predicted == 0 and cryptoAmount > 0:
                  dlrsAmount = dlrsAmount + cryptoAmount * closePrice
                  cryptoAmount = 0
      
      return (dlrsAmount, cryptoAmount)


def calculateSum(predicted, dlrsAmount, cryptoAmount, closePrice, investedPart):
      pass

In [27]:

dlrsAmount, cryptoAmount = calculateDollars(1000, 0.5)
print('dlrsAmount', dlrsAmount)
print('cryptoAmount', cryptoAmount)

dlrsAmount 11191.351725284243
cryptoAmount 0